export const cities = [
  {
    city: 'Zagreb',
    lat: '45.8167',
    lng: '15.9833',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Rijeka',
    lat: '45.3272',
    lng: '14.4411',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Split',
    lat: '43.5100',
    lng: '16.4400',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Osijek',
    lat: '45.5556',
    lng: '18.6944',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Zadar',
    lat: '44.1194',
    lng: '15.2319',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Sesvete',
    lat: '45.8269',
    lng: '16.1111',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Velika Gorica',
    lat: '45.7000',
    lng: '16.0667',
    country: 'Croatia',
    parking: 'not available',
  },
  {
    city: 'Pula',
    lat: '44.8703',
    lng: '13.8456',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Slavonski Brod',
    lat: '45.1667',
    lng: '18.0167',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Karlovac',
    lat: '45.4833',
    lng: '15.5500',
    country: 'Croatia',
    parking: 'not available',
  },
  {
    city: 'Šibenik',
    lat: '43.7350',
    lng: '15.8906',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Kaštel Stari',
    lat: '43.5500',
    lng: '16.3500',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Dubrovnik',
    lat: '42.6403',
    lng: '18.1083',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Bjelovar',
    lat: '45.9000',
    lng: '16.8333',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Varaždin',
    lat: '46.3081',
    lng: '16.3378',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Sisak',
    lat: '45.4872',
    lng: '16.3761',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Vinkovci',
    lat: '45.2911',
    lng: '18.8011',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Koprivnica',
    lat: '46.1500',
    lng: '16.8167',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Čakovec',
    lat: '46.3858',
    lng: '16.4333',
    country: 'Croatia',
    parking: 'not available',
  },
  {
    city: 'Ðakovo',
    lat: '45.3100',
    lng: '18.4100',
    country: 'Croatia',
    parking: 'not available',
  },
  {
    city: 'Zaprešić',
    lat: '45.8572',
    lng: '15.8050',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Vukovar',
    lat: '45.3444',
    lng: '19.0025',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Sinj',
    lat: '43.7000',
    lng: '16.6333',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Petrinja',
    lat: '45.4406',
    lng: '16.2783',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Solin',
    lat: '43.5317',
    lng: '16.4947',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Kutina',
    lat: '45.4667',
    lng: '16.7833',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Požega',
    lat: '45.3331',
    lng: '17.6736',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Virovitica',
    lat: '45.8333',
    lng: '17.3833',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Dugo Selo',
    lat: '45.8058',
    lng: '16.2331',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Sveti Ivan Zelina',
    lat: '45.9596',
    lng: '16.2431',
    country: 'Croatia',
    'iso2': 'HR',
    parking: 'not available',
  },
  {
    city: 'Jastrebarsko',
    lat: '45.6719',
    lng: '15.6511',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Metković',
    lat: '43.0500',
    lng: '17.6500',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Samobor',
    lat: '45.8000',
    lng: '15.7167',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Omiš',
    lat: '43.4333',
    lng: '16.6833',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Vrbovec',
    lat: '45.8833',
    lng: '16.4333',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Ivanić-Grad',
    lat: '45.7081',
    lng: '16.3947',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Viškovo',
    lat: '45.3778',
    lng: '14.3861',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Rovinj',
    lat: '45.0833',
    lng: '13.6333',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Makarska',
    lat: '43.3000',
    lng: '17.0333',
    country: 'Croatia',
    parking: 'not available',
  },
  {
    city: 'Ivanec',
    lat: '46.2264',
    lng: '16.1253',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Trogir',
    lat: '43.5169',
    lng: '16.2514',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Novi Marof',
    lat: '46.1667',
    lng: '16.3333',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Umag',
    lat: '45.4333',
    lng: '13.5167',
    country: 'Croatia',
    'iso2': 'HR',
    parking: 'available',
  },
  {
    city: 'Krapina',
    lat: '46.1600',
    lng: '15.8700',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Županja',
    lat: '45.0700',
    lng: '18.7000',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Nedelišće',
    lat: '46.3833',
    lng: '16.3833',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Popovača',
    lat: '45.5697',
    lng: '16.6250',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Nova Gradiška',
    lat: '45.2500',
    lng: '17.3833',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Opatija',
    lat: '45.3333',
    lng: '14.3000',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Labin',
    lat: '45.0833',
    lng: '14.1167',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Valpovo',
    lat: '45.6667',
    lng: '18.4167',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Matulji',
    lat: '45.3667',
    lng: '14.3167',
    country: 'Croatia',
    parking: 'not available',
  },
  {
    city: 'Križevci',
    lat: '46.0258',
    lng: '16.5425',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Crikvenica',
    lat: '45.1833',
    lng: '14.7000',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Knin',
    lat: '44.0414',
    lng: '16.1986',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Duga Resa',
    lat: '45.4472',
    lng: '15.4958',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Kastav',
    lat: '45.3750',
    lng: '14.3490',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Garešnica',
    lat: '45.5667',
    lng: '16.9333',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Slatina',
    lat: '45.7022',
    lng: '17.7011',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Beli Manastir',
    lat: '45.7667',
    lng: '18.6000',
    country: 'Croatia',
    parking: 'not available',
  },
  {
    city: 'Daruvar',
    lat: '45.5929',
    lng: '17.2237',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Čepin',
    lat: '45.5167',
    lng: '18.5667',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Trilj',
    lat: '43.6167',
    lng: '16.7167',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Zabok',
    lat: '46.0333',
    lng: '15.9167',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Pazin',
    lat: '45.2403',
    lng: '13.9367',
    country: 'Croatia',
    parking: 'not available',
  },
  {
    city: 'Ludbreg',
    lat: '46.2500',
    lng: '16.6100',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Lepoglava',
    lat: '46.2074',
    lng: '16.0437',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Ðurđevac',
    lat: '46.0272',
    lng: '17.0672',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Mali Lošinj',
    lat: '44.5333',
    lng: '14.4667',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Čazma',
    lat: '45.7500',
    lng: '16.6167',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Bedekovčina',
    lat: '46.0333',
    lng: '16.0000',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Rab',
    lat: '44.7561',
    lng: '14.7611',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Našice',
    lat: '45.4833',
    lng: '18.1000',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Poreč',
    lat: '45.2272',
    lng: '13.5958',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Drniš',
    lat: '43.8625',
    lng: '16.1556',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Križ',
    lat: '45.6500',
    lng: '16.5167',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Erdut',
    lat: '45.5333',
    lng: '19.0667',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Čavle',
    lat: '45.3569',
    lng: '14.4878',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Dugi Rat',
    lat: '43.2620',
    lng: '16.6210',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Novska',
    lat: '45.3333',
    lng: '16.9833',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Prelog',
    lat: '46.3333',
    lng: '16.6167',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Trnovec Bartolovečki',
    lat: '46.2947',
    lng: '16.3989',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Brckovljani',
    lat: '45.8300',
    lng: '16.3000',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Pregrada',
    lat: '46.1600',
    lng: '15.7500',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Vrgorac',
    lat: '43.2000',
    lng: '17.3667',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Ploče',
    lat: '43.0500',
    lng: '17.4333',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Belišće',
    lat: '45.6833',
    lng: '18.4000',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Medulin',
    lat: '44.8219',
    lng: '13.9350',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Maruševec',
    lat: '46.2900',
    lng: '16.1800',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Mursko Središće',
    lat: '46.5000',
    lng: '16.4333',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Krk',
    lat: '45.0167',
    lng: '14.5667',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Donji Miholjac',
    lat: '45.7500',
    lng: '18.1500',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Ivankovo',
    lat: '45.2833',
    lng: '18.6833',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Lipik',
    lat: '45.4150',
    lng: '17.1600',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Ozalj',
    lat: '45.6129',
    lng: '15.4777',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Buzet',
    lat: '45.4167',
    lng: '13.9667',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Vodice',
    lat: '43.7500',
    lng: '15.7667',
    country: 'Croatia',
    parking: 'not available',
  },
  {
    city: 'Kloštar Ivanić',
    lat: '45.7400',
    lng: '16.4200',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Gospić',
    lat: '44.5460',
    lng: '15.3750',
    country: 'Croatia',
    parking: 'not available',
  },
  {
    city: 'Donja Stubica',
    lat: '45.9800',
    lng: '15.9700',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Cestica',
    lat: '46.3700',
    lng: '16.1200',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Korčula',
    lat: '42.9500',
    lng: '17.1250',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Biograd na Moru',
    lat: '43.9391',
    lng: '15.4474',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Mala Subotica',
    lat: '46.3833',
    lng: '16.5333',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Jelenje',
    lat: '45.3833',
    lng: '14.4667',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Darda',
    lat: '45.6261',
    lng: '18.6925',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Buje',
    lat: '45.4167',
    lng: '13.6667',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Ilok',
    lat: '45.2219',
    lng: '19.3753',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Borovo',
    lat: '45.3833',
    lng: '18.9667',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Veliko Trgovišće',
    lat: '46.0000',
    lng: '15.8500',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Gornji Kneginec',
    lat: '46.2500',
    lng: '16.3700',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Sračinec',
    lat: '46.3294',
    lng: '16.2789',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Rovišće',
    lat: '45.9500',
    lng: '16.7333',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Petrijanec',
    lat: '46.3500',
    lng: '16.2300',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Imotski',
    lat: '43.4500',
    lng: '17.2167',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Donji Kraljevec',
    lat: '46.3700',
    lng: '16.6500',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Kraljevica',
    lat: '45.2667',
    lng: '14.5667',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Delnice',
    lat: '45.4000',
    lng: '14.8000',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Stari Jankovci',
    lat: '45.2667',
    lng: '18.9167',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Sukošan',
    lat: '44.0490',
    lng: '15.3120',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Vela Luka',
    lat: '42.9611',
    lng: '16.7194',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Hvar',
    lat: '43.1714',
    lng: '16.4433',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Kostrena',
    lat: '45.3072',
    lng: '14.4983',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Orebić',
    lat: '42.9667',
    lng: '17.1667',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Lovran',
    lat: '45.2920',
    lng: '14.2740',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Bednja',
    lat: '46.2300',
    lng: '15.9800',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Bibinje',
    lat: '44.0717',
    lng: '15.2878',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Ližnjan',
    lat: '44.8333',
    lng: '13.9500',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Orahovica',
    lat: '45.5329',
    lng: '17.8795',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Jakovlje',
    lat: '45.9500',
    lng: '15.8500',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Marčana',
    lat: '44.9500',
    lng: '13.9500',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Bošnjaci',
    lat: '45.0500',
    lng: '18.7667',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Podturen',
    lat: '46.4667',
    lng: '16.5500',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Martijanec',
    lat: '46.2667',
    lng: '16.5333',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Skradin',
    lat: '43.8167',
    lng: '15.9167',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Preko',
    lat: '44.0864',
    lng: '15.1828',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Sveti Ðurđ',
    lat: '46.2844',
    lng: '16.6042',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Josipdol',
    lat: '45.1886',
    lng: '15.2848',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Gunja',
    lat: '44.8967',
    lng: '18.8500',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Novalja',
    lat: '44.5500',
    lng: '14.8833',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Nuštar',
    lat: '45.3333',
    lng: '18.8333',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Jalžabet',
    lat: '46.2600',
    lng: '16.4800',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Babina Greda',
    lat: '45.1167',
    lng: '18.5333',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Vodnjan',
    lat: '44.9667',
    lng: '13.8500',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Martinska Ves',
    lat: '45.5800',
    lng: '16.3700',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Dugopolje',
    lat: '43.5803',
    lng: '16.5969',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Lipovljani',
    lat: '45.4000',
    lng: '16.8900',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Nova Rača',
    lat: '45.8000',
    lng: '16.9500',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Oroslavje',
    lat: '46.0000',
    lng: '15.9100',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Gradac',
    lat: '43.1061',
    lng: '17.3411',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Opuzen',
    lat: '43.0176',
    lng: '17.5623',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Kotoriba',
    lat: '46.3500',
    lng: '16.8167',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Supetar',
    lat: '43.3844',
    lng: '16.5553',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Pag',
    lat: '44.4435',
    lng: '15.0545',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Tisno',
    lat: '43.8000',
    lng: '15.6500',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Davor',
    lat: '45.1167',
    lng: '17.5167',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Primošten',
    lat: '43.5833',
    lng: '15.9333',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Omišalj',
    lat: '45.2119',
    lng: '14.5542',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Privlaka',
    lat: '45.1943',
    lng: '18.8378',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Kršan',
    lat: '45.1733',
    lng: '14.1392',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Ražanac',
    lat: '44.2833',
    lng: '15.3500',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Ivanska',
    lat: '45.7833',
    lng: '16.8167',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Šenkovec',
    lat: '46.4167',
    lng: '16.4167',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Netretić',
    lat: '45.5094',
    lng: '15.4125',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Goričan',
    lat: '46.3833',
    lng: '16.6833',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Stubičke Toplice',
    lat: '45.9758',
    lng: '15.9322',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Starigrad',
    lat: '43.1833',
    lng: '16.5833',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Baška Voda',
    lat: '43.3575',
    lng: '16.9492',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Tovarnik',
    lat: '45.1667',
    lng: '19.1500',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Gradište',
    lat: '45.1500',
    lng: '18.7100',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Hrvatska Kostajnica',
    lat: '45.2333',
    lng: '16.5333',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Nin',
    lat: '44.2333',
    lng: '15.1833',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Veliko Trojstvo',
    lat: '45.9333',
    lng: '16.9333',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Ravna Gora',
    lat: '45.3667',
    lng: '14.9333',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Barban',
    lat: '45.1000',
    lng: '14.0167',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Dežanovac',
    lat: '45.5667',
    lng: '17.0833',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Suhopolje',
    lat: '45.8000',
    lng: '17.5000',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Orehovica',
    lat: '46.3300',
    lng: '16.5100',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Strahoninec',
    lat: '46.3667',
    lng: '16.4167',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Krašić',
    lat: '45.6500',
    lng: '15.5167',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Zlatar Bistrica',
    lat: '46.0600',
    lng: '16.0700',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Klanjec',
    lat: '46.0467',
    lng: '15.7361',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Strizivojna',
    lat: '45.2300',
    lng: '18.4200',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Budinšćina',
    lat: '46.1100',
    lng: '16.2000',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Donji Andrijevci',
    lat: '45.1833',
    lng: '18.3000',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Jarmina',
    lat: '45.3167',
    lng: '18.7333',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Rešetari',
    lat: '45.1500',
    lng: '17.2700',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Kutjevo',
    lat: '45.4333',
    lng: '17.8833',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Sibinj',
    lat: '45.1917',
    lng: '17.9081',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Runović',
    lat: '43.3833',
    lng: '17.2167',
    country: 'Croatia',
    'iso2': 'HR',
    parking: 'available',
  },
  {
    city: 'Stari Mikanovci',
    lat: '45.2833',
    lng: '18.5500',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Koprivnički Ivanec',
    lat: '46.2000',
    lng: '16.8167',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Končanica',
    lat: '45.6379',
    lng: '17.1646',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Rogoznica',
    lat: '43.5333',
    lng: '15.9694',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Sveta Marija',
    lat: '46.3333',
    lng: '16.7333',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Petrijevci',
    lat: '45.6167',
    lng: '18.5333',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Višnjan',
    lat: '45.2761',
    lng: '13.7200',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Domašinec',
    lat: '46.4333',
    lng: '16.6000',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Legrad',
    lat: '46.3000',
    lng: '16.8500',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Mali Bukovec',
    lat: '46.2800',
    lng: '16.7400',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Cavtat',
    lat: '42.5794',
    lng: '18.2208',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Vrbanja',
    lat: '44.9833',
    lng: '18.9333',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Svetvinčenat',
    lat: '45.0833',
    lng: '13.8833',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Breznica',
    lat: '46.0700',
    lng: '16.2700',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Beretinec',
    lat: '46.2486',
    lng: '16.3061',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Slavonski Šamac',
    lat: '45.0667',
    lng: '18.4833',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Štitar',
    lat: '45.1000',
    lng: '18.6333',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Velika',
    lat: '45.4556',
    lng: '17.6625',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Tuhelj',
    lat: '46.0769',
    lng: '15.7472',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Marija Gorica',
    lat: '45.9200',
    lng: '15.7300',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Dobrinj',
    lat: '45.1300',
    lng: '14.6040',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Cerna',
    lat: '45.1903',
    lng: '18.6889',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Andrijaševci',
    lat: '45.2167',
    lng: '18.7333',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Bizovac',
    lat: '45.5900',
    lng: '18.4600',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Gundinci',
    lat: '45.1500',
    lng: '18.4833',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Gornji Stupnik',
    lat: '45.7667',
    lng: '15.8500',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Kravarsko',
    lat: '45.5800',
    lng: '16.0400',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Vratišinec',
    lat: '46.4833',
    lng: '16.4500',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Bukovlje',
    lat: '45.1900',
    lng: '18.0700',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Punat',
    lat: '45.0147',
    lng: '14.6289',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Vođinci',
    lat: '45.2756',
    lng: '18.6097',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Bogdanovci',
    lat: '45.3333',
    lng: '18.9333',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Drenovci',
    lat: '44.9200',
    lng: '18.8500',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Farkaševac',
    lat: '45.8806',
    lng: '16.6358',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Vis',
    lat: '43.0667',
    lng: '16.1833',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Tučepi',
    lat: '43.2667',
    lng: '17.0500',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Pirovac',
    lat: '43.8167',
    lng: '15.6667',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Gornja Vrba',
    lat: '45.1500',
    lng: '18.0667',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Jakšić',
    lat: '45.3600',
    lng: '17.7600',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Drnje',
    lat: '46.2100',
    lng: '16.9200',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Selca',
    lat: '43.2950',
    lng: '16.8470',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Sikirevci',
    lat: '45.1167',
    lng: '18.4667',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Brela',
    lat: '43.3697',
    lng: '16.9225',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Varaždinske Toplice',
    lat: '46.2081',
    lng: '16.4214',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Velika Kopanica',
    lat: '45.1500',
    lng: '18.4000',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Vrpolje',
    lat: '45.2106',
    lng: '18.4056',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Tinjan',
    lat: '45.2172',
    lng: '13.8389',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Preseka',
    lat: '45.9667',
    lng: '16.3833',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Bol',
    lat: '43.2667',
    lng: '16.6500',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Brtonigla',
    lat: '45.3833',
    lng: '13.6333',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Feričanci',
    lat: '45.5300',
    lng: '17.9800',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Cernik',
    lat: '45.2900',
    lng: '17.3800',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Brodski Stupnik',
    lat: '45.1667',
    lng: '17.8000',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Breznički Hum',
    lat: '46.1044',
    lng: '16.2806',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Staro Petrovo Selo',
    lat: '45.2333',
    lng: '17.5167',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Bakar',
    lat: '45.3278',
    lng: '14.5361',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Postire',
    lat: '43.3833',
    lng: '16.6333',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Kanfanar',
    lat: '45.1167',
    lng: '13.8333',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Tribunj',
    lat: '43.7700',
    lng: '15.9169',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Mošćenička Draga',
    lat: '45.2333',
    lng: '14.2500',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Ðelekovec',
    lat: '46.2500',
    lng: '16.8700',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Komiža',
    lat: '43.0500',
    lng: '16.1000',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Lopar',
    lat: '44.8300',
    lng: '14.7300',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Visoko',
    lat: '46.0903',
    lng: '16.3250',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Negoslavci',
    lat: '45.2833',
    lng: '19.0000',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Veliki Bukovec',
    lat: '46.3000',
    lng: '16.7167',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Karojba',
    lat: '45.3000',
    lng: '13.8167',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Bedenica',
    lat: '46.0223',
    lng: '16.2639',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Donji Vidovec',
    lat: '46.3333',
    lng: '16.7833',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Luka',
    lat: '45.9700',
    lng: '15.8200',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Gračišće',
    lat: '45.2194',
    lng: '14.0103',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Donja Motičina',
    lat: '45.4900',
    lng: '18.0200',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Vižinada',
    lat: '45.3333',
    lng: '13.7667',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Viškovci',
    lat: '45.3400',
    lng: '18.4500',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Vladislavci',
    lat: '45.4600',
    lng: '18.5700',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Sveti Petar u Šumi',
    lat: '45.1833',
    lng: '13.8667',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Lokve',
    lat: '45.3581',
    lng: '14.7481',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Ernestinovo',
    lat: '45.4500',
    lng: '18.6600',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Smokvica',
    lat: '42.9292',
    lng: '16.8953',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Markušica',
    lat: '45.3738',
    lng: '18.7062',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Zagorska Sela',
    lat: '46.0969',
    lng: '15.6350',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Motovun',
    lat: '45.3333',
    lng: '13.8333',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Malinska',
    lat: '45.1333',
    lng: '14.5333',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Lopatinec',
    lat: '46.4331',
    lng: '16.3831',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Garčin',
    lat: '45.1819',
    lng: '18.1839',
    country: 'Croatia',
    'iso2': 'HR',
    parking: 'available',
  },
  {
    city: 'Zrinski Topolovac',
    lat: '46.0333',
    lng: '16.7167',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Tar',
    lat: '45.2989',
    lng: '13.6250',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Trpanj',
    lat: '43.0000',
    lng: '17.2750',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Lovas',
    lat: '45.2333',
    lng: '19.1667',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Mikleuš',
    lat: '45.6200',
    lng: '17.8000',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Funtana',
    lat: '45.1667',
    lng: '13.6000',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Donja Pušća',
    lat: '45.9167',
    lng: '15.7833',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Dekanovec',
    lat: '46.4500',
    lng: '16.5833',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Povljana',
    lat: '44.3467',
    lng: '15.1156',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Tordinci',
    lat: '45.3667',
    lng: '18.8000',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Kukljica',
    lat: '44.0350',
    lng: '15.2464',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Gornji Bogičevci',
    lat: '45.2600',
    lng: '17.2300',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Punitovci',
    lat: '45.4333',
    lng: '18.4167',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Nedeščina',
    lat: '45.1400',
    lng: '14.1139',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Drenje',
    lat: '45.3800',
    lng: '18.2800',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Dragalić',
    lat: '45.2467',
    lng: '17.2889',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Vlaka',
    lat: '43.0094',
    lng: '17.5256',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Kaštelir',
    lat: '45.3031',
    lng: '13.6850',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Sveti Martin na Muri',
    lat: '46.5269',
    lng: '16.3750',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Klakar',
    lat: '45.1000',
    lng: '18.1333',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Podstrana',
    lat: '43.4800',
    lng: '16.5800',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Kaštel Sućurac',
    lat: '43.5500',
    lng: '16.4261',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Sveta Nedjelja',
    lat: '45.7983',
    lng: '15.7806',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Okrug Gornji',
    lat: '43.4969',
    lng: '16.2200',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Privlaka',
    lat: '44.2590',
    lng: '15.1290',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Donji Seget',
    lat: '43.5167',
    lng: '16.2333',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Petrovsko',
    lat: '46.1600',
    lng: '15.8400',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Sveti Ilija',
    lat: '46.2450',
    lng: '16.3381',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Pribislavec',
    lat: '46.3925',
    lng: '16.4825',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Srebreno',
    lat: '42.6233',
    lng: '18.1961',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Vir',
    lat: '44.3034',
    lng: '15.0855',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Hum na Sutli',
    lat: '46.2139',
    lng: '15.6903',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Vidovec',
    lat: '46.2833',
    lng: '16.2411',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Sveti Križ Začretje',
    lat: '46.0800',
    lng: '15.9100',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Galovac',
    lat: '44.0714',
    lng: '15.3933',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Poljanica Bistranska',
    lat: '45.9000',
    lng: '15.8833',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Ðurmanec',
    lat: '46.2000',
    lng: '15.8400',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Vrsar',
    lat: '45.1500',
    lng: '13.6100',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Selnica',
    lat: '46.4961',
    lng: '16.4036',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Kali',
    lat: '44.0633',
    lng: '15.2067',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Špišić-Bukovica',
    lat: '45.8561',
    lng: '17.3000',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Bilice',
    lat: '43.7753',
    lng: '15.9181',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Zmijavci',
    lat: '43.4108',
    lng: '17.2056',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Krapinske Toplice',
    lat: '46.1000',
    lng: '15.8500',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Lumbarda',
    lat: '42.9220',
    lng: '17.1700',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Sveti Filip i Jakov',
    lat: '43.9614',
    lng: '15.4248',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Gornja Stubica',
    lat: '45.9600',
    lng: '16.0300',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Radoboj',
    lat: '46.1664',
    lng: '15.9236',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Belica',
    lat: '46.4042',
    lng: '16.5183',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Podbablje',
    lat: '43.4169',
    lng: '17.1761',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Vinica',
    lat: '46.3361',
    lng: '16.1494',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Kraljevec na Sutli',
    lat: '45.9800',
    lng: '15.7300',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Donja Dubrava',
    lat: '46.3147',
    lng: '16.8119',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Dubravica',
    lat: '45.9500',
    lng: '15.7333',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Rugvica',
    lat: '45.7361',
    lng: '16.2331',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Mače',
    lat: '46.0900',
    lng: '16.0300',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Koprivnički Bregi',
    lat: '46.1333',
    lng: '16.9000',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Škabrnje',
    lat: '44.0916',
    lng: '15.4516',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Konjšćina',
    lat: '46.0700',
    lng: '16.1800',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Murter',
    lat: '43.8204',
    lng: '15.5899',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Vrsi',
    lat: '44.2667',
    lng: '15.2333',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Novi Golubovec',
    lat: '46.1800',
    lng: '15.9800',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Lobor',
    lat: '46.1500',
    lng: '16.0600',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Zlatar',
    lat: '46.1500',
    lng: '16.1167',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Pakoštane',
    lat: '43.9094',
    lng: '15.5081',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Klinča Sela',
    lat: '45.6800',
    lng: '15.7500',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Klenovnik',
    lat: '46.2700',
    lng: '16.0700',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Donja Voća',
    lat: '46.3000',
    lng: '16.1000',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Antunovac',
    lat: '45.4900',
    lng: '18.6800',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Pitomača',
    lat: '45.9506',
    lng: '17.2294',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Desinić',
    lat: '46.1400',
    lng: '15.6600',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Gornje Jesenje',
    lat: '46.2064',
    lng: '15.9125',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Kloštar Podravski',
    lat: '45.9833',
    lng: '17.1500',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Podravske Sesvete',
    lat: '46.0000',
    lng: '17.2167',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Posedarje',
    lat: '44.2167',
    lng: '15.4833',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Polača',
    lat: '44.0167',
    lng: '15.5167',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Otok',
    lat: '43.6914',
    lng: '16.7383',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Ðurđenovac',
    lat: '45.5400',
    lng: '18.0500',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Virje',
    lat: '46.0672',
    lng: '16.9900',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Poličnik',
    lat: '44.1833',
    lng: '15.3833',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Mihovljan',
    lat: '46.1331',
    lng: '15.9722',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Peteranec',
    lat: '46.2000',
    lng: '16.8833',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Ljubešćica',
    lat: '46.1667',
    lng: '16.3833',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Donji Proložac',
    lat: '43.4667',
    lng: '17.1500',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Orle',
    lat: '45.6800',
    lng: '16.2300',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Žminj',
    lat: '45.1500',
    lng: '13.9167',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Hrašćina',
    lat: '46.1100',
    lng: '16.2200',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Vuka',
    lat: '45.4339',
    lng: '18.5050',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Novigrad',
    lat: '44.1942',
    lng: '15.5567',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Sveti Ivan Žabno',
    lat: '45.9500',
    lng: '16.6167',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Sveti Petar Orehovec',
    lat: '46.0833',
    lng: '16.4500',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Gornja Rijeka',
    lat: '46.1167',
    lng: '16.4000',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Kamanje',
    lat: '45.6333',
    lng: '15.4000',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Dubrava',
    lat: '45.8381',
    lng: '16.5439',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Molve',
    lat: '46.1167',
    lng: '17.0333',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Kalnik',
    lat: '46.1167',
    lng: '16.4667',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Raša',
    lat: '45.0806',
    lng: '14.0847',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Pašman',
    lat: '43.9569',
    lng: '15.3800',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Kalinovac',
    lat: '46.0333',
    lng: '17.1167',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Sutivan',
    lat: '43.3833',
    lng: '16.4833',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Zadvarje',
    lat: '43.4314',
    lng: '16.8897',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Zemunik Donji',
    lat: '44.1067',
    lng: '15.3806',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Novo Virje',
    lat: '46.0983',
    lng: '17.1550',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Hercegovac',
    lat: '45.6667',
    lng: '17.0167',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Gradec',
    lat: '45.9111',
    lng: '16.4828',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Kraj',
    lat: '43.6375',
    lng: '16.5819',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Draganići',
    lat: '45.6000',
    lng: '15.6000',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Lukač',
    lat: '45.8700',
    lng: '17.4200',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Otok',
    lat: '45.1467',
    lng: '18.8839',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Hlebine',
    lat: '46.1539',
    lng: '16.9661',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Blato',
    lat: '42.9408',
    lng: '16.7917',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Kaptol',
    lat: '45.4347',
    lng: '17.7261',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Klis',
    lat: '43.5667',
    lng: '16.5167',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Lećevica',
    lat: '43.6489',
    lng: '16.3489',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Novigrad Podravski',
    lat: '46.0833',
    lng: '16.9500',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Marina',
    lat: '43.5141',
    lng: '16.1082',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Rakovec',
    lat: '45.9303',
    lng: '16.3225',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Ferdinandovac',
    lat: '46.0500',
    lng: '17.2000',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Gola',
    lat: '46.1958',
    lng: '17.0581',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Pićan',
    lat: '45.2000',
    lng: '14.0500',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Popovac',
    lat: '45.8092',
    lng: '18.6583',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Grohote',
    lat: '43.3833',
    lng: '16.2833',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Stankovci',
    lat: '43.9167',
    lng: '15.7000',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Severin',
    lat: '45.8369',
    lng: '16.9592',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Gorjani',
    lat: '45.4000',
    lng: '18.3700',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Nova Kapela',
    lat: '45.1989',
    lng: '17.6392',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Gradina',
    lat: '45.8550',
    lng: '17.5072',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Milna',
    lat: '43.4000',
    lng: '16.3267',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Štefanje',
    lat: '45.8000',
    lng: '16.7200',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Žakanje',
    lat: '45.6000',
    lng: '15.3400',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Rasinja',
    lat: '46.1839',
    lng: '16.7067',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Kolan',
    lat: '44.4833',
    lng: '14.9500',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Lekenik',
    lat: '45.5833',
    lng: '16.2167',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Podgora',
    lat: '43.2433',
    lng: '17.0772',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Pisarovina',
    lat: '45.5872',
    lng: '15.8583',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Velika Ludina',
    lat: '45.6000',
    lng: '16.6000',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Kapela',
    lat: '45.9881',
    lng: '16.8517',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Bribir',
    lat: '45.1611',
    lng: '14.7647',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Kula Norinska',
    lat: '43.0290',
    lng: '17.6050',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Pakrac',
    lat: '45.4389',
    lng: '17.1917',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Primorski Dolac',
    lat: '43.6308',
    lng: '16.1761',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Lokvičič',
    lat: '43.5000',
    lng: '17.0600',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Generalski Stol',
    lat: '45.3400',
    lng: '15.3800',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Šandrovac',
    lat: '45.9000',
    lng: '17.0167',
    country: 'Croatia',
    parking: 'available',
  },
  {
    city: 'Sokolovac',
    lat: '46.1108',
    lng: '16.7064',
    country: 'Croatia',
    parking: 'available',
  },
];
